DELETE http://localhost:3003/api/blogs/641713bc6f26574a6be24be0
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkcG81IiwiaWQiOiI2NDE2ZTQxNzU1MjY1OGUxYWRiODU5ZDYiLCJpYXQiOjE2NzkyMzUxMDZ9.o6ywYF0nLdtIzYMBigXz-J5kbSByEUmErph2I6FC1RA